// Generated by CoffeeScript 1.4.0
var Mixer;

Mixer = (function() {

  function Mixer() {}

  Mixer.gens = [];

  Mixer.tmpL = new Float32Array(pico.cellsize);

  Mixer.tmpR = new Float32Array(pico.cellsize);

  Mixer.add = function(gen) {
    return gens.push(gen);
  };

  Mixer.remove = function(gen) {
    var i;
    i = gens.indexOf(gen);
    if (i !== -1) {
      return gens.splice(i, 1);
    }
  };

  Mixer.process = function(L, R) {
    var i, j, _i, _j, _ref, _ref1, _results;
    for (i = _i = 0, _ref = L.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      L[i] = R[i] = 0;
    }
    _results = [];
    for (i = _j = 0, _ref1 = gens.length; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
      gens[i].process(tmpL, tmpR);
      _results.push((function() {
        var _k, _ref2, _results1;
        _results1 = [];
        for (j = _k = j, _ref2 = L.length; j <= _ref2 ? _k <= _ref2 : _k >= _ref2; j = j <= _ref2 ? ++_k : --_k) {
          L[j] += tmpL[j];
          _results1.push(R[j] += tmpR[j]);
        }
        return _results1;
      })());
    }
    return _results;
  };

  return Mixer;

})();
